services:
  mysql:
    image: mysql:8.0
    container_name: skygym-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-p${DB_ROOT_PASS}']
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
